### ISSUE TITLE
Add support for multiple tags, tags without values

### ISSUE THREAD

**Issue by ryanlawson** [ryanlawson/greenswitch#1]
Currently GreenSwitch only performs filtering on the `Name` tag (i.e. the instance name). I would like to support filtering based on multiple tags.

Additionally, I would like to be able to filter based on just the presence of a tag, with no value to compare.

Idea for new configuration:

```yaml
GreenSwitch:
  handler: greenswitch.handler
  events:
    - schedule:
       rate: cron(0 20 ? * 2-6 *)
       enabled: true
       input:
         Action: ON|OFF
         Tags:
           TagName: TagValue
           TagName
```

I do _not_ know if filtering is based on `AND` or `OR`, but a third `Criteria: AND|OR` parameter may be required.

I also don't know how `TagName` without an associated value is represented in the Event.
