### ISSUE TITLE
Add support for opt-out approach based on tags

### ISSUE THREAD

**Issue by ryanlawson** [ryanlawson/greenswitch#2]
Currently GreenSwitch only matches on the presence of certain tags (e.g. requires an opt-in). I want to be able to support an opt-out feature, so only instances _without_ a certain tag are affected. This could benefit accounts with a large number of instances or with frequent turnover.

Idea for new configuration:

```yaml
GreenSwitch:
  handler: greenswitch.handler
  events:
    - schedule:
       rate: cron(0 20 ? * 2-6 *)
       enabled: true
       input:
         Action: ON|OFF
         Opt: IN|OUT
           Tags: TagValue1,TagValue2,TagValue3
         Tags:
           TagName: TagValue
           TagName
```
